
drop sequence NOTICE_SEQ;
drop sequence REPORTDETAIL_SEQ;
drop sequence REPORT_SEQ;
drop sequence REPLY_SEQ;
drop sequence BOARD_PR_SEQ;
drop sequence BOARD_FREE_SEQ;
drop sequence BOARD_NOTI_SEQ;
drop sequence BOARD_FAQ_SEQ;
drop sequence BOARD_QNA_SEQ;

drop sequence RMEMO_SEQ;
drop sequence REVIEW_SEQ;
drop sequence RESERVATION_SEQ;
drop sequence TRANSFER_SEQ;
drop sequence INOUT_SEQ;
drop sequence ASSET_SEQ;

DROP TABLE NOTICE;
DROP TABLE REPORTDETAIL;
DROP TABLE EMEMO;
DROP TABLE RMEMO;
DROP TABLE REVIEW;
DROP TABLE RESERVATION;
DROP TABLE TRANSFER;
DROP TABLE INOUT;
DROP TABLE ASSET;
DROP TABLE EXPERT;
DROP TABLE REPORT;
DROP TABLE REPLY;
DROP TABLE BOARD;
DROP TABLE MEMBER;
DROP TABLE CODE;

PURGE RECYCLEBIN;
select * from tab;